### ISSUE TITLE
Змініть ліцензію з "BY-NC-ND 3.0" на "BY-NC-SA 3.0"

### ISSUE THREAD

**Issue by ghost** [LambdaBooks/dictionary#34]
> Якщо Ви помітили яку-небудь помилку, повідомте нас, або виправте та надішліть пул–реквест.

На даний час вказана ліцензія ("[BY-NC-ND 3.0](https://creativecommons.org/licenses/by-nc-nd/3.0/deed.en_US)") не дозволяє робити пул-реквести:

> **NoDerivatives** — If you remix, transform, or build upon the material, you may not distribute the modified material. 

Будь-ласка, змініть ліцензію проекту на "[BY-NC-SA 3.0](https://creativecommons.org/licenses/by-nc-sa/3.0/deed.en_US)" яка дозволить приймати участь у покращенні словника і іншим учасникам!

> **ShareAlike** — If you remix, transform, or build upon the material, you must distribute your contributions under the same license as the original.

**Comment by denysdovhan** [comment]
Хороше зауваження! Готово! 

Напевно нам слід змінити ліцензії і для інших проектів?

**Comment by ghost** [comment]
> Напевно нам слід змінити ліцензії і для інших проектів?

Було б добре ;-)

**Comment by denysdovhan** [comment]
Готово!
